# Generated by Django 3.1.4 on 2020-12-30 23:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='results',
            name='arabic',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='art',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='math',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='results',
            name='science',
            field=models.IntegerField(null=True),
        ),
    ]
