# Generated by Django 3.1.1 on 2020-12-31 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20201231_0131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='number',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
