# Generated by Django 3.1.4 on 2021-01-04 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_auto_20210102_0844'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='number',
            field=models.PositiveIntegerField(default='', null=True),
        ),
    ]
