# Generated by Django 3.1.4 on 2021-01-04 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210104_0259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='result',
            name='number',
            field=models.CharField(max_length=8, null=True),
        ),
    ]
